### ISSUE TITLE
博客首页的avatar404了

### ISSUE THREAD

**Issue by bluestudyhard** [Chilfish/chilfish.top#3]
rt
![image](https://github.com/Chilfish/chilfish.top/assets/98652207/9b68cb0d-13e6-4ae9-ba63-d6d8d9ea3d79)
and different between
![image](https://github.com/Chilfish/chilfish.top/assets/98652207/1880e620-4c4d-49f6-b084-1bbcfc2b7ceb)

**Comment by Chilfish** [comment]
这是因为pwa的缓存问题。旧版使用了pwa，新版没，上图你看到的是旧版的缓存，清空网页数据再刷新就行了🤨
